import java.util.*;
class Prime
{
    void main()
    {
        Scanner sc=new Scanner(System.in);
        int i,m=0, flag=0;
        int n=3; //it is the number to be checked
        m=n/2;
        if(n==0&n==1){
            System.out.println(n+ "is not a prime number");
        }else{
            for(i=2;i<=m;i++){
                if(n%i==0){
                    System.out.println(n+ "is not a prime number");
                    flag=1;
                    break;
                }
            }
        if(flag==0) 
        { System.out.println(n+ "is a prime number");}
        }//end of else
    }//end of method
}//end of class
